name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy-linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Run the Cake script
          uses: cake-build/cake-action@v1
          with:
            script-path: build.cake
            verbosity: Verbose
            arguments: |
              version: ${{ github.ref }}
        - name: Release files
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              ./publish/imager-${{ github.ref }}-linux-x64.zip
              ./publish/imager-${{ github.ref }}-linux-arm64.zip
  deploy-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: build.cake
          verbosity: Verbose
          arguments: |
            version: ${{ github.ref }}
      - name: Release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./publish/imager-${{ github.ref }}-osx-x64.zip
            ./publish/imager-${{ github.ref }}-osx-arm64.zip
  deploy-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          script-path: build.cake
          verbosity: Verbose
          arguments: |
            version: ${{ github.ref }}
      - name: Release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./publish/imager-${{ github.ref }}-win-x64.zip

